# 1. URL de Conexão (Baseada no seu DIRECT_URL)
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require

# 2. Usuário (O que vem logo após o 'postgres.' no seu código)
spring.datasource.username=postgres.lvcptyahlgxichovfqhz

# 3. A SENHA (A que você definiu na criação. Se não lembrar, clique em "Reset Password")
spring.datasource.password=Cunegundes*19

# 4. Configurações de Driver e Dialeto (Postgres)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 5. O "Pulo do Gato": Isso cria as tabelas do seu TCC automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL no console para você saber que está funcionando
spring.jpa.show-sql=true