name: Build and deploy JAR app to Azure Web App - gadysback

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests

      - name: Prepare deploy package
        run: |
          mkdir deploy
          cp target/gadys-backend-0.0.1-SNAPSHOT.jar deploy/app.jar
          cp web.config deploy/web.config

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gadysback'
          slot-name: 'Production'
          package: deploy
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_93EAFBA5958E471CA82CDB6F22D2515E }}
